services:
  react-dev:
    profiles:
      - dev
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "dev", "--host"]

  react-prod:
    profiles:
      - prod
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    restart: always